### ISSUE TITLE
Hangs if creating relationship in open transaction

### ISSUE THREAD

**Issue by subvertallchris** [graphaware/neo4j-timetree#12]
Not sure if this is something to fix or just note, but it appears that if you POST to link an event to the tree while a transaction is open, it will timeout.

Running 2.1.7 Enterprise with in Neo4j Server mode.

**Comment by bachmanm** [comment]
definitely something to look at, will do that asap, thanks!

**Comment by bachmanm** [comment]
What's happening is that there is an open long-running transaction that holds a lock on the just created event. Another transaction is created when POSTing to TimeTree, which tries to lock the event node as well so it can attach it. But it can't, hence waiting...

Long-term solution would be to find a way to bind open long-running transactions created using the transactional endpoint to the current thread when consuming an extension API, so that the extension (TimeTree in this case) can participate in the transaction. I checked how hard it would be to do in Neo4j 2.2 and haven't cracked it... would be very hacky. I will try to issue a pull request to Neo4j that makes this possible for extensions to do.

In the mid-term, TimeTree will provide a way (in the 2.2 release) to automatically attach events (i.e. nodes with certain labels, specified by you) to the tree in the same transaction, using GraphAware Runtime (i.e. Tx event handlers). This will require the events to have a timestamp property.

In the short-term, I'm afraid two different transactions will have to do. This is something that was also raised earlier by @ikwattro, so it is on our list. We'll try to find the best solution.

Cheers, Michal

**Comment by bachmanm** [comment]
see https://github.com/graphaware/neo4j-framework/issues/15

**Comment by subvertallchris** [comment]
Great, I really appreciate you looking into this so quickly.

**Comment by bachmanm** [comment]
closing this, leaving https://github.com/graphaware/neo4j-framework/issues/15 open

**Comment by bachmanm** [comment]
fixed, will be released with 2.2
