### ISSUE TITLE
Support additional resolutions

### ISSUE THREAD

**Issue by bachmanm** [graphaware/neo4j-timetree#15]
investigate supporting quarters, weeks, etc.

**Comment by asianfilm** [comment]
Beyond the resolutions of quarters and weeks, there are other time periods one may wish to connect to. For a film releasing calendar, movies are sometimes scheduled for "summer" release. We can go by the solstices to give a default summer range. But a film in Hong Kong may be announced to open during the 2016 Chinese New Year (which has different dates depending on its year). Similarly, a film in Japan may be set for release during 2015 Golden Week. I guess "Easter" is similar. In summary, we may want for the user to define their own ranges, if these aren't built in.

I'm not sure what the opposite of "resolution" is, but there's another useful scenario. One often may now that an actor is born on 16 June, but not the year and you may want to record that in the time tree graph. You may want a list of all people with the "born" event on 16 June, irrespective of which year, including those born on 16 June whose year of birth you don't know. One could implement it by creating a "yearless month" node with value "6" (for June) whose children are the time nodes representing 16 June 2014, 16 June 2015, etc, assuming they exist in the time tree already. (In the diagram, all arrows represent directed "child" relationships. For clarity, I'm not showing "next", "first" or "last" relationships.)


![yearless_month](https://cloud.githubusercontent.com/assets/890222/7220513/6dc0be08-e6fc-11e4-90ec-1834ac446b46.png)

**Comment by bachmanm** [comment]
Very good ideas, thanks! We will address this but it is not sure when exactly. Stay tuned!

**Comment by moshebeeri** [comment]
Cool idea, I was thinking that it will be nice to have other time frames on the leaf, like 10 seconds

**Comment by Joshfindit** [comment]
I came here for exactly the same request, but for another reason:

Historical "accuracy" (which is say; the lack of it). I've been normally calling this 'fuzzy time' because we may know what day an event occurred, what season, what quarter, or what decade. There may be ways to narrow it down, or there may only be a general idea based on some clues ("it was snowing when..."). We're historically a very fuzzy species.

Iian Neill of http://the-codex.net has done some excellent thinking on this while working with Neo4j, and he shares most of it in this video introduction: https://www.youtube.com/watch?v=_R0ESfLBuHo

**Comment by bachmanm** [comment]
Closing until an enterprise customer requests this (no time :()
