### ISSUE TITLE
Getting back uid instead of nodeId

### ISSUE THREAD

**Issue by Bretto** [graphaware/neo4j-timetree#37]
I am using my own uid as i read nodeId (may) be volatile (what is the status on that btw...) so I am wondering how I can get my uid instead of the nodeId as a result from TT module ?

**Comment by bachmanm** [comment]
Internal node IDs may (at some point in the future) be volatile but only in the presence of DB restarts. Using them for TT is safe. That said, your approach to use own uids is a valid one and we also know of people who want to combine the TT module with our UUID module.

I think the fix is easy, we should return the entire node serialised into JSON, rather than just the ID. Feel free to do a PR, otherwise I will fix this in August.

If you are doing a PR, have a look at this: http://graphaware.com/site/framework/latest/apidocs/com/graphaware/api/JsonNode.html (should be easily serialisable using Jackson).

**Comment by bachmanm** [comment]
Fix released in a few minutes
