### ISSUE TITLE
Automatic Event Attachment is not working

### ISSUE THREAD

**Issue by moshebeeri** [graphaware/neo4j-timetree#40]
I am using latest versions of neo4j, and graphaware software, the event has time stamp as configured in neo4j.properties file and it is labeled as should.
From what I understands from the documentation, creating new node labeled with com.graphaware.module.TT.event=hasLabel('eve`nt')
and has the right timestamp com.graphaware.module.TT.timestamp=timestamp
should result in creation of the new node the time tree nodes that are missing and the relationship between the new node and the time tree.
Either there is a bug in the code or in the docs, any advice?
this is my configuration:
![screen shot 2015-08-06 at 3 44 52 pm](https://cloud.githubusercontent.com/assets/574405/9112723/fe4ed17e-3c58-11e5-9e2a-b377c046e550.png)

this is the event:
![screen shot 2015-08-06 at 4 36 12 pm](https://cloud.githubusercontent.com/assets/574405/9112759/53ac33b4-3c59-11e5-9e6d-ac8c3bc3af9c.png)

What is wrong?

**Comment by bachmanm** [comment]
First of all, the latest version of Neo4j you should be using is 2.2.2. GraphAware is not compatible with 2.2.3 due to this bug: https://github.com/neo4j/neo4j/issues/4910. Please make sure you use 2.2.2.

Secondly, why do you specify TimeTreeRoot in your config, when there is no such property on the event?

Other than that, it should work, please report back once you've fixed the above. Thanks

**Comment by moshebeeri** [comment]
Michal thanks for the quick replies, it works like charm :-) :+1:

**Comment by bachmanm** [comment]
Good :)
