### ISSUE TITLE
Possible to attach multiple events in one POST?

### ISSUE THREAD

**Issue by Jiropole** [graphaware/neo4j-timetree#50]
First, thank you for this amazing module – it really saves labor! And honestly, I'm new enough to Neo4j I don't know how to build such a sophisticated tree on the fly.

To my problem: I have a case where I'm importing a large amount of data. While I am planning to use automatic event connection, my dates are incomplete at the time the imported event nodes are created (using LOAD CSV). I have to run a second sweep to fix all my bad dates, so I've already lost the chance to have the time tree nodes auto-connected to events on CREATE. I see I can POST to _/graphaware/timetree/single/event_ to have these reconnected, but it looks like I have to make a single POST for each event, which on a tight loop can really tax the http connection pool. I can probably address this by serializing the POST requests, but it seems like a much better solution would be for these calls to support an array of events in the post body, rather than only handling one at a time.

Is this already a feature, and I missed it in the documentation? Or what do you think about this enhancement?

**Comment by ikwattro** [comment]
Hi, The auto event attachments will work when you update nodes as well, so the events will be attached when your times will be ok, before that you might get a log message in the log files that the current timestamp has an invalid format.

We don't support batch operations via the REST API. And to be honest, since the auto-attachment possibility and the upcoming Stored Procedures in Neo4j 3.0, I don't think we will add such improvements to the current status of the API (except maybe in case of paid consultancy)

Let us know if you have success by updating your node properties while using the auto-attachment setup.

**Comment by Jiropole** [comment]
Ah, most impressive. I just ran that test and it built the same tree it was building with my many explicit http requests, in much less time. Would you mind updating the auto-attachment documentation in your README, perhaps changing the line "By default, any node created with label Event that contains a property..." to say "created or updated"? Just to save someone else wandering down this rabbit-hole. 

On a related note, the documentation was unclear to me on the best way to instantiate the module multiple times, in order to have different relationship labels. I followed the pattern in the example, as I understood it. Is the idea to choose arbitrary permutations of e.g. 'TT', followed by an increasing index number, as shown below? It works, I just wasn't sure *why* it worked.

com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
...
com.graphaware.module.TS.2=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
...
com.graphaware.module.TR.3=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

Thanks again for your fast support and excellent module.

**Comment by bachmanm** [comment]
"TT" (or "TS" etc in your case) is just an ID of the module that the framework uniquely identifies it with. Can be any String really and doesn't mean anything, as long as it is unique. 

The number is the order in which the modules get applied. In your case (3 TimeTree modules), it doesn't matter, because the end result is the same no matter which order they are applied in.
