### ISSUE TITLE
Timestamp range not working

### ISSUE THREAD

**Issue by kingo999** [graphaware/neo4j-timetree#80]
Hello,
I have 3 events created at various times.
When I run a query to get back just one the events inside a time range it always returns all three events:
For example
```
CALL ga.timetree.events.range({start: 1572986213510, end: timestamp()})

CALL ga.timetree.events.range({start: 1572986213517, end: 1572986213517})

CALL ga.timetree.events.range({start: 1572986213516, end: 1572986213516})
```

If I run
`CALL ga.timetree.events.single({time: 1572986213517})`
It still returns all 3 ???

Results:
```
{   "uuid": "c5636ce0-0007-11ea-9971-025041000001",   "ref": 0,   "timestamp": 1572984395420 } 

{   "ref": 20,   "relationshipType": "USER_CREATED_ON",   "uuid": "456e8cc0-0009-11ea-9971-025041000001",   "timestamp": 1572985040767 }

{   "uuid": "007051f1-000c-11ea-9971-025041000001",   "ref": 20,   "timestamp": 1572986213516 }
```

**Comment by aldrinm** [comment]
What time resolution have you setup? The default resolution is `Day`. Since all those timestamps fall on the same day (5 Nov GMT), they are all matched and returned.

If you want to query at the millisecond level, you can specify a resolution while attaching the events and while querying. For example,

`CREATE (e:Email {text: "I used the timetree"}) WITH e
CALL ga.timetree.events.attach({node: e, time: 1463659567468, relationshipType: "SENT_ON", resolution: "Millisecond"})
YIELD node RETURN node`

and

`CALL ga.timetree.events.range({start: 1572986213510, end: timestamp(), resolution: 'Millisecond'})
`
